---
###############################################################################
# Configure Services
###############################################################################
# Filetree returns a dict (instead of a list of dict) for one element. Use
# query to guarantee a list result. Traefik configuration may contain nested
# directories.
#
# Reference:
# * https://betatim.github.io/posts/traefik-config-bare-metal

- name: '{{ "Config | filesystem | set " ~ traefik___app._etc_d }}'
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ traefik___app._etc_d ~ "/" ~ item.path }}'
        owner: '{{ traefik__srv._user }}'
        group: '{{ traefik__srv._group }}'
        mode: '0750'
        state: 'directory'
      loop: '{{ query("community.general.filetree", traefik__cfg._d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ traefik___app._etc_d ~ "/" ~ item.path }}'
        owner: '{{ traefik__srv._user }}'
        group: '{{ traefik__srv._group }}'
        mode: '0640'
      loop: '{{ query("community.general.filetree", traefik__cfg._d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ traefik___app._etc_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: traefik__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ traefik__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", traefik__cfg._d) |
          map(attribute='path') |
          map('regex_replace', '^', traefik___app._etc_d ~ "/") | list
        )
