---
- name: 'Prep'
  ansible.builtin.import_tasks: 'prep.yml'

- name: 'Maintenance'
  when: traefik_flg_maintenance
  ansible.builtin.import_tasks: 'maintenance.yml'

- name: 'Install'
  when: traefik_flg_install
  ansible.builtin.import_tasks: 'install.yml'

- name: 'Config'
  when: traefik_flg_config
  ansible.builtin.import_tasks: 'config.yml'

- name: 'Services'
  ansible.builtin.import_tasks: 'services.yml'
- name: 'Start'
  ansible.builtin.import_tasks: 'start.yml'
