---
###############################################################################
# Default
###############################################################################
# Default configuration is deployed successfully.
#
# Tests:
# * Traefik running (will not start with invalid config) for both toml/yaml
#   static configurations.
# * Traefik started/restarted correctly.
# * Dashboard is accessible at http://localhost:8080/dashboard/.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        molecule_flg_inject: true
        traefik_flg_config: true
        traefik_cfg_d: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/templates/default"
          }}'
        traefik_cfg_env:
          - var: 'GCE_PROJECT'
            value: 'my-project-id-123456789'
          - var: 'GCE_SERVICE_ACCOUNT_FILE'
            value: '/etc/opt/traefik/gcloud_dns.json'
platforms:
  - name: 'traefik-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - 'SYS_ADMIN'  # Required for testing systemd hardening.
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '8080:8080/tcp'
      - '8443:443/tcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
