---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | query dashboard toml'
      ansible.builtin.uri:
        url: 'http://localhost:8080/dashboard/'
        method: 'GET'
        status_code: 200
